sudo: false

language: node_js

node_js:
  - "stable"

env:
  matrix:
    - CI_TEACHER_ACCOUNT=d3V4aSBoYW5odWFxaWFuZw==
    - CI_TEACHER_ACCOUNT=emhvbmdzaGFuIGdvbmdoYW5odWkzNTMx
    - CI_TEACHER_ACCOUNT=emhvbmdzaGFuIGh1bWluMTk4MDEwMjc=
    - CI_TEACHER_ACCOUNT=emhvbmdzaGFuIGh1eWkxNDkwMTc5
    - CI_TEACHER_ACCOUNT=emhvbmdzaGFuIGNoZW5kb25ncWluMTA3Mg==
    - CI_TEACHER_ACCOUNT=emhvbmdzaGFuIHpoYW9zaGFubGFu
    - CI_TEACHER_ACCOUNT=Y2hlbmdkdSB6aGFvbGluZzQwMDQ=

matrix:
  fast_finish: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # give xvfb some time to start
  - sleep 3

script:
  - npm test
  - travis_retry npm run -s start
