dist: trusty
sudo: false

language: node_js

node_js:
  - "stable"

env:
  - DISPLAY=:99.0

before_install:
  - if [ $TRAVIS_EVENT_TYPE == "cron" ] && [[ $TRAVIS_JOB_NUMBER =~ \.1$ ]]; then
      npm run daocloud;
    fi
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
  - chmod +x run.sh
  - ./run.sh
